# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  desc "Assemble Build"
  lane :assemble_build do |options|
      gradle(
        task: "assemble",
        flavor: options[:build_flavor],
        build_type: options[:build_type]
      )
  end

  desc "Run Unit Tests"
  lane :unit_tests do |options|
    gradle(
        task: "test",
        flavor: options[:build_flavor],
        build_type: options[:build_type]
      )
    end

  desc "Beta Deployment"
  lane :beta do |options|
    assemble_build(build_flavor:"Beta", build_type:"Release")
    upload_to_play_store(
        track: 'Beta track',
        apk: Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
  end

  desc "Run tests on AWS Device Farm"
  lane :aws_device_run_android do
    ENV['AWS_REGION']            = 'us-west-2'
  
    #Build Debug App + Instrumentation Apk
    gradle(task: 'assembleDebug')
    gradle(task: 'assembleAndroidTest')
  
    # RUN tests on AWS Device Farm
    aws_device_farm(
      name:                 'pinwheel-android',
      device_pool:          'android-devices',
      binary_path:          'app/build/outputs/apk/dev/debug/app-dev-debug.apk',
      test_binary_path:     'app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk'
    )
  end
end

